### ISSUE TITLE
aabb_wrap.cxx missing

### ISSUE THREAD

**Issue by classner** [lohedges/aabbcc#1]
Hi!

Thank you for sharing the library! Just noticed that `aabb_wrap.cxx' for the python wrapper is missing (referenced in setup.py).

Best!

**Comment by lohedges** [comment]
Hi there,

The aabb_wrap.cxx file is automatically generated by SWIG when creating the python wrapper, it is not part of the repository itself. I'm guessing that you don't have SWIG installed (or it's not in your path) so the python library fails to build (because of the missing aabb_wrap.cxx file). Have a look at the "python" recipe in the Makefile to see what's going on (lines 243-248). First SWIG creates the appropriate wrapper files from the source code, then python uses these files to build the wrapper library.

Hope this helps,
Lester

**Comment by classner** [comment]
Ahhh, great! Thank you for the quick reply!
