### ISSUE TITLE
how to draw a tree to see the hierarchy like "middle image"?

### ISSUE THREAD

**Issue by sume-cn** [lohedges/aabbcc#21]
as the title says

**Comment by lohedges** [comment]
Hello there,

Thanks for the question. The image was drawn using custom code using the [VMD](http://www.ks.uiuc.edu/Research/vmd/) package. There is no code to do this for you included with the library since, so you'd need to write something yourself. While it would potentially be a useful feature, it would be hard to generalise since the code works in arbitrary dimension.

Hope this helps.
