### ISSUE TITLE
Null check wrong place

### ISSUE THREAD

**Issue by kujukuju** [lohedges/aabbcc#22]
Hey, just a heads up that I think you want to be null checking before you access the elements
https://github.com/lohedges/aabbcc/blob/master/src/AABB.cc#L620-L622

**Comment by lohedges** [comment]
Hi there, thanks for your question. The order in the code is correct. This isn't like a null pointer, rather nodes that are not currently in use are flagged as being a `NULL_NODE`. This allows us to use a `vector` to store the nodes and resize it dynamically whenever the node capacity is exceeded. The lines that you highlight are being used to skip to the top of the loop if we encounter a `NULL_NODE` in our makeshift stack when performing a query. This will occur once we've traversed a branch of the tree and reached a leaf, since the left- and right-hand children are `NULL_NODE`.

Hope this helps.
