### ISSUE TITLE
custom query help !!

### ISSUE THREAD

**Issue by EpicSpaces** [lohedges/aabbcc#23]
I really loved your library, simple and easy to use, I was dying for months to make my own spatial partitioning, I was almost going to hang myself.
from now I would love to make a query that sort all the particles in regard to the given index of current particle. (of course by the closest distance)
I'm a little stuck. and thanks

**Comment by lohedges** [comment]
Hi there. I'm not sure I 100% understand what you are intending to do. From my reading it seems like you want to query the tree to find the candidate "items" that overlap, then sort these according to their distance from the reference "item". (I say "item", since these can be arbitrary objects, not just particles.) If this is the case, then it's not something that can be done within the AABB code, since it requires knowledge about the shape of the objects in question. You would need to write your own code to loop over the candidate items that are returned, work out the distance from the reference, then sort them. There is code in the examples that shows how to check for actual overlaps in a 2D particle example, which involves computing the distance of each candidate from the reference, e.g. [here](https://github.com/lohedges/aabbcc/blob/master/python/hard_disc.py) and [here](https://github.com/lohedges/aabbcc/blob/master/demos/hard_disc.cc). You could adapt this for your own purposes. If you only care about the distance of the AABBs themselves, i.e. the centre of each AABB from the reference, then it would be possible to add a `sort` option to the `Tree::query` method, that sorts the AABBs by distance before returning the candidate items.

Cheers.

**Comment by lohedges** [comment]
Hi there,

Did this help solve your issue? If so, feel free to close.

Cheers.

**Comment by lohedges** [comment]
Closing as sensible suggestion made and no response from original poster. Please feel free to re-open if you have further questions.
